services:
  db:
    image: postgres:17.5
    container_name: postgres_17_5
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: ./app
    container_name: app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - images:/app/images
    working_dir: /app
    command: [ "python", "-u", "app.py" ]

  nginx:
    image: nginx:latest
    container_name: image_nginx
    ports:
      - "8080:80"
    volumes:
      - images:/app/images
      - logs:/var/log/nginx
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    depends_on:
      - app
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - chmod -R 775 /app/images /var/log/nginx && ln -sf /dev/stdout /var/log/nginx/access.log && ln -sf /dev/stderr /var/log/nginx/error.log && ln -sf /dev/stdout /var/log/nginx/images.log && nginx -g 'daemon off;'

      # Команда ln -sf /dev/stdout /var/log/nginx/images.log перенаправляет image-логи Nginx в stdout (терминал).
      # Команда ln -sf /dev/stdout /var/log/nginx/access.log перенаправляет access-логи Nginx в stdout (терминал).
      # Команда ln -sf /dev/stderr /var/log/nginx/error.log — перенаправляет error-логи в stderr (терминал).
      # И логи по-прежнему будут записываться в ./logs/nginx/app.log

volumes:
  images:
  logs:
  pg_data: